apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
      - name: rsvp-app 
        image: teamcloudyuga/rsvpapp
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: TEXT1
          valueFrom:
            configMapKeyRef:
              name: customer1
              key: TEXT1
        - name: TEXT2 
          valueFrom:
            configMapKeyRef:
              name: customer1 
              key: TEXT2
        - name: COMPANY 
          valueFrom:
            configMapKeyRef:
              name: customer1 
              key: COMPANY
        ports:
        - containerPort: 5000
